# Generated by Django 3.0.8 on 2020-08-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filelinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=10, verbose_name='Metric No')),
                ('file_name', models.CharField(max_length=300, verbose_name='File name')),
                ('file_link', models.CharField(max_length=300, verbose_name='File link')),
            ],
        ),
        migrations.CreateModel(
            name='M111m12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=10, verbose_name='Metric No')),
                ('description_500wrds', models.TextField(default='nil000nul', verbose_name='Description 500 words')),
            ],
        ),
        migrations.CreateModel(
            name='M113',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=10, verbose_name='Metric No')),
                ('option', models.CharField(max_length=30, verbose_name='Option')),
                ('year', models.CharField(max_length=10, verbose_name='Year')),
                ('month', models.CharField(max_length=10, verbose_name='Month')),
                ('department', models.CharField(max_length=30, verbose_name='Department')),
                ('teacher_name', models.CharField(max_length=100, verbose_name='Teacher name')),
                ('partcipated_body', models.CharField(max_length=200, verbose_name='Paricipated institute/body name')),
            ],
        ),
        migrations.CreateModel(
            name='M121',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=10, verbose_name='Metric No')),
                ('program_code', models.CharField(default='nil000nul', max_length=100, verbose_name='Program Code')),
                ('program_name', models.CharField(max_length=200, verbose_name='Program Name')),
                ('year', models.CharField(max_length=10, verbose_name='Introduction Year')),
                ('month', models.CharField(max_length=10, verbose_name='Introduction Month')),
                ('implment_status', models.CharField(max_length=5, verbose_name='Implementation Status')),
                ('implment_year', models.CharField(max_length=10, verbose_name='Implemented Year')),
                ('implment_month', models.CharField(max_length=10, verbose_name='Implemented Month')),
            ],
        ),
        migrations.CreateModel(
            name='M122',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=10, verbose_name='Metric No')),
                ('year', models.CharField(max_length=10, verbose_name='Introduction Year')),
                ('month', models.CharField(max_length=10, verbose_name='Introduction Month')),
                ('course_name', models.CharField(max_length=200, verbose_name='Add on/Certificate Course Name')),
                ('course_code', models.CharField(default='nil000nul', max_length=100, verbose_name='Program Code')),
                ('department', models.CharField(max_length=30, verbose_name='Department')),
                ('offered_year', models.CharField(max_length=10, verbose_name='Offered Year')),
                ('offered_month', models.CharField(max_length=10, verbose_name='Offered Month')),
                ('offered_times', models.IntegerField(verbose_name='No of times per year')),
                ('course_duration', models.CharField(max_length=20, verbose_name='Course Duration')),
                ('enrolled_students_no', models.IntegerField(verbose_name='Enrolled number of Students')),
                ('completed_students_no', models.IntegerField(verbose_name='Completed number of Students in the Year')),
            ],
        ),
        migrations.CreateModel(
            name='M123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=10, verbose_name='Metric No')),
                ('year', models.CharField(max_length=10, verbose_name='Offered Year')),
                ('enrolled_students_no', models.IntegerField(verbose_name='Enrolled number of Students')),
            ],
        ),
    ]
