# Generated by Django 3.0.8 on 2020-08-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cri1app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m113',
            name='partcipated_body',
        ),
        migrations.AddField(
            model_name='m113',
            name='participated_body',
            field=models.CharField(default='MES', max_length=200, verbose_name='Participated institute/body name'),
        ),
        migrations.AddField(
            model_name='m121',
            name='program_totalNo',
            field=models.IntegerField(default=0, verbose_name='Total Programs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m122',
            name='course_totalNo',
            field=models.IntegerField(default=0, verbose_name='Total Courses'),
            preserve_default=False,
        ),
    ]
